services:
  - type: web
    name: ip-tracker-bot
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn tracker:app
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: BASE_URL
        sync: false 